# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable

FILES      = main ../../controller/depdiamond ../../controller/diamond ../../controller/dep
